### ISSUE TITLE
[suggestion] string field for moves, "looksLike" for a text description of what the move looks like

### ISSUE THREAD

**Issue by goudekid** [fANZYo/T7api#1]
It's always irked me that most times people talk about moves for characters you don't play, they'll say oh b3,1+2 is -11 on block. Okay, now I either have to go to the lab to see what this one move is, or go through the hell of finding a youtube video that might have it definitively labeled. If we could at least have an optional field that just says "left leg knee into overhead two-hand slam" or something that'd be superb.

**Comment by fANZYo** [comment]
That's a good idea, would having the name of the move as labeled in the tekken practice movelist solve this problem?

**Comment by goudekid** [comment]
I'd say move name in addition to that field, not in place of it. The major reason I want something like that is so that I can pull up a movelist mid-deathmatch and figure out from what the move looks like what it is and it's properties right then, without having to stop my deathmatch.  

Clearly this data would have to be filled in manually, but since it only needs to be done once per move it's a small price to pay to have instant access to a move without knowing it's notation or name. I also want to mention that I'll probably start filling in moves on and off if the field was included, and I am only requesting the field be created, not that you personally go through every character's movelist and describe the moves yourself.

**Comment by fANZYo** [comment]
Hey @goudekid, I've added the field. I've created a branch `feature/moveDescription` for you to add the descriptions.

**Comment by fANZYo** [comment]
Closed because inactive.
